runtime: python39
service: route-optimization

handlers:
- url: /static
  static_dir: app/static
  secure: always

- url: /.*
  script: auto
  secure: always

env_variables:
  FLASK_ENV: "production"
  
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 3
